# Docker Compose file for running the Spring Boot application and PostgreSQL database

version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: productsearch # Set the database name
      POSTGRES_USER: postgres # Set the database user
      POSTGRES_PASSWORD: password # Set the database password
    ports:
      - "5432:5432" # Expose the PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist database data

  app:
    build: . # Build the Docker image from the Dockerfile in the current directory
    ports:
      - "8080:8080" # Expose the application port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/productsearch # Set the datasource URL
      SPRING_DATASOURCE_USERNAME: postgres # Set the datasource username
      SPRING_DATASOURCE_PASSWORD: password # Set the datasource password
    depends_on:
      - db # Ensure the database service is started before the application

volumes:
  postgres_data: